name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make
      
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependecies
      run: |
        make install
    
    - name: Linting
      run: |
        make lint
    
    - name: Test
        run:|
          make test
        
